/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as StedenRouteImport } from './routes/steden'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRestaurantsDotxmlRouteImport } from './routes/sitemap-restaurants[.]xml'
import { Route as SitemapLandingDotxmlRouteImport } from './routes/sitemap-landing[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as StadCityRouteImport } from './routes/stad.$city'
import { Route as RestaurantSlugRouteImport } from './routes/restaurant.$slug'
import { Route as KeukenCuisineRouteImport } from './routes/keuken.$cuisine'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LangStedenRouteImport } from './routes/$lang.steden'
import { Route as LangStadCityRouteImport } from './routes/$lang.stad.$city'
import { Route as LangRestaurantSlugRouteImport } from './routes/$lang.restaurant.$slug'
import { Route as LangKeukenCuisineRouteImport } from './routes/$lang.keuken.$cuisine'

const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const StedenRoute = StedenRouteImport.update({
  id: '/steden',
  path: '/steden',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRestaurantsDotxmlRoute =
  SitemapRestaurantsDotxmlRouteImport.update({
    id: '/sitemap-restaurants.xml',
    path: '/sitemap-restaurants.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapLandingDotxmlRoute = SitemapLandingDotxmlRouteImport.update({
  id: '/sitemap-landing.xml',
  path: '/sitemap-landing.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const StadCityRoute = StadCityRouteImport.update({
  id: '/stad/$city',
  path: '/stad/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSlugRoute = RestaurantSlugRouteImport.update({
  id: '/restaurant/$slug',
  path: '/restaurant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KeukenCuisineRoute = KeukenCuisineRouteImport.update({
  id: '/keuken/$cuisine',
  path: '/keuken/$cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LangStedenRoute = LangStedenRouteImport.update({
  id: '/$lang/steden',
  path: '/$lang/steden',
  getParentRoute: () => rootRouteImport,
} as any)
const LangStadCityRoute = LangStadCityRouteImport.update({
  id: '/$lang/stad/$city',
  path: '/$lang/stad/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRestaurantSlugRoute = LangRestaurantSlugRouteImport.update({
  id: '/$lang/restaurant/$slug',
  path: '/$lang/restaurant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangKeukenCuisineRoute = LangKeukenCuisineRouteImport.update({
  id: '/$lang/keuken/$cuisine',
  path: '/$lang/keuken/$cuisine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-landing.xml': typeof SitemapLandingDotxmlRoute
  '/sitemap-restaurants.xml': typeof SitemapRestaurantsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/steden': typeof StedenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/$lang/steden': typeof LangStedenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/keuken/$cuisine': typeof KeukenCuisineRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/stad/$city': typeof StadCityRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/keuken/$cuisine': typeof LangKeukenCuisineRoute
  '/$lang/restaurant/$slug': typeof LangRestaurantSlugRoute
  '/$lang/stad/$city': typeof LangStadCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-landing.xml': typeof SitemapLandingDotxmlRoute
  '/sitemap-restaurants.xml': typeof SitemapRestaurantsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/steden': typeof StedenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/$lang/steden': typeof LangStedenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/keuken/$cuisine': typeof KeukenCuisineRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/stad/$city': typeof StadCityRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/keuken/$cuisine': typeof LangKeukenCuisineRoute
  '/$lang/restaurant/$slug': typeof LangRestaurantSlugRoute
  '/$lang/stad/$city': typeof LangStadCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-landing.xml': typeof SitemapLandingDotxmlRoute
  '/sitemap-restaurants.xml': typeof SitemapRestaurantsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/steden': typeof StedenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/$lang/steden': typeof LangStedenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/keuken/$cuisine': typeof KeukenCuisineRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/stad/$city': typeof StadCityRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/keuken/$cuisine': typeof LangKeukenCuisineRoute
  '/$lang/restaurant/$slug': typeof LangRestaurantSlugRoute
  '/$lang/stad/$city': typeof LangStadCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap-landing.xml'
    | '/sitemap-restaurants.xml'
    | '/sitemap.xml'
    | '/steden'
    | '/voorwaarden'
    | '/$lang/steden'
    | '/admin'
    | '/keuken/$cuisine'
    | '/restaurant/$slug'
    | '/stad/$city'
    | '/$lang/'
    | '/$lang/keuken/$cuisine'
    | '/$lang/restaurant/$slug'
    | '/$lang/stad/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap-landing.xml'
    | '/sitemap-restaurants.xml'
    | '/sitemap.xml'
    | '/steden'
    | '/voorwaarden'
    | '/$lang/steden'
    | '/admin'
    | '/keuken/$cuisine'
    | '/restaurant/$slug'
    | '/stad/$city'
    | '/$lang'
    | '/$lang/keuken/$cuisine'
    | '/$lang/restaurant/$slug'
    | '/$lang/stad/$city'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap-landing.xml'
    | '/sitemap-restaurants.xml'
    | '/sitemap.xml'
    | '/steden'
    | '/voorwaarden'
    | '/$lang/steden'
    | '/_authenticated/admin'
    | '/keuken/$cuisine'
    | '/restaurant/$slug'
    | '/stad/$city'
    | '/$lang/'
    | '/$lang/keuken/$cuisine'
    | '/$lang/restaurant/$slug'
    | '/$lang/stad/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapLandingDotxmlRoute: typeof SitemapLandingDotxmlRoute
  SitemapRestaurantsDotxmlRoute: typeof SitemapRestaurantsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StedenRoute: typeof StedenRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  LangStedenRoute: typeof LangStedenRoute
  KeukenCuisineRoute: typeof KeukenCuisineRoute
  RestaurantSlugRoute: typeof RestaurantSlugRoute
  StadCityRoute: typeof StadCityRoute
  LangIndexRoute: typeof LangIndexRoute
  LangKeukenCuisineRoute: typeof LangKeukenCuisineRoute
  LangRestaurantSlugRoute: typeof LangRestaurantSlugRoute
  LangStadCityRoute: typeof LangStadCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steden': {
      id: '/steden'
      path: '/steden'
      fullPath: '/steden'
      preLoaderRoute: typeof StedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-restaurants.xml': {
      id: '/sitemap-restaurants.xml'
      path: '/sitemap-restaurants.xml'
      fullPath: '/sitemap-restaurants.xml'
      preLoaderRoute: typeof SitemapRestaurantsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-landing.xml': {
      id: '/sitemap-landing.xml'
      path: '/sitemap-landing.xml'
      fullPath: '/sitemap-landing.xml'
      preLoaderRoute: typeof SitemapLandingDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stad/$city': {
      id: '/stad/$city'
      path: '/stad/$city'
      fullPath: '/stad/$city'
      preLoaderRoute: typeof StadCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$slug': {
      id: '/restaurant/$slug'
      path: '/restaurant/$slug'
      fullPath: '/restaurant/$slug'
      preLoaderRoute: typeof RestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuken/$cuisine': {
      id: '/keuken/$cuisine'
      path: '/keuken/$cuisine'
      fullPath: '/keuken/$cuisine'
      preLoaderRoute: typeof KeukenCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$lang/steden': {
      id: '/$lang/steden'
      path: '/$lang/steden'
      fullPath: '/$lang/steden'
      preLoaderRoute: typeof LangStedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/stad/$city': {
      id: '/$lang/stad/$city'
      path: '/$lang/stad/$city'
      fullPath: '/$lang/stad/$city'
      preLoaderRoute: typeof LangStadCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/restaurant/$slug': {
      id: '/$lang/restaurant/$slug'
      path: '/$lang/restaurant/$slug'
      fullPath: '/$lang/restaurant/$slug'
      preLoaderRoute: typeof LangRestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/keuken/$cuisine': {
      id: '/$lang/keuken/$cuisine'
      path: '/$lang/keuken/$cuisine'
      fullPath: '/$lang/keuken/$cuisine'
      preLoaderRoute: typeof LangKeukenCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapLandingDotxmlRoute: SitemapLandingDotxmlRoute,
  SitemapRestaurantsDotxmlRoute: SitemapRestaurantsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StedenRoute: StedenRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  LangStedenRoute: LangStedenRoute,
  KeukenCuisineRoute: KeukenCuisineRoute,
  RestaurantSlugRoute: RestaurantSlugRoute,
  StadCityRoute: StadCityRoute,
  LangIndexRoute: LangIndexRoute,
  LangKeukenCuisineRoute: LangKeukenCuisineRoute,
  LangRestaurantSlugRoute: LangRestaurantSlugRoute,
  LangStadCityRoute: LangStadCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
